# in .github/ranger.yaml
labels:
  accepted:
    action: close
    delay: 0s
    comment: "🎉 Your request was accepted, thank you for contributing!"
  duplicate:
    action: close
    delay: 0s
    comment: "⚠️ Your request has been removed for being duplicate, next time please check if domain that you want to report was not already reported before creating new one."
  rejected:
    action: close
    delay: 0s
    comment: "🚫 Your request was denied, please don't open issue with same domain again! If you think there was an error, comment below and issue will be reviewed again."
